### ISSUE TITLE
Project creation: organization_id vs organizations_id

### ISSUE THREAD

**Issue by pedromg** [teambox/redbooth-ruby#22]
project = client.project(:create, organization_id: 491277, name: "P1", publish_pages: false)

Documentation (https://redbooth.com/api/api-docs/#page:projects) mentions: organizations_id

(plural vs singular)

**Comment by csaura** [comment]
It's `organization_id`. We will update the documentation, thanks

**Comment by csaura** [comment]
The documentation has been updated, thanks a lot for let us know this issue. Happy hacking!
